#!/bin/sh
# Pack a project under the name of top directory
# Save it under ../topdirname.tar.gz

# Getting top directory name:
VER2=`pwd | cut -d '/' -f 4`; 
cd ..  
echo Compressing files in $VER2
tar czf $VER2.tar.gz  $VER2/*
cd $VER2
mv ../$VER2.tar.gz .
echo Done.

