# GitHub actions workflow.
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Build+Test CI

on:
  push:
    branches: [main, gh-actions]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  Linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - run: sudo apt-get install -y libfl-dev
    - uses: actions/checkout@v7
    - run: make distcheck
    - name: Dump testsuite log
      if: failure()
      run: cat ptest/testsuite.log

  macOS:
    strategy:
      matrix:
        os: [macos-latest]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - run: brew install autoconf bison flex
    - uses: actions/checkout@v7
    - run: make
    - run: make check
    - name: Dump testsuite log
      if: failure()
      run: cat ptest/testsuite.log

  Windows:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }
      fail-fast: false
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{matrix.sys}}
        install: >-
          autoconf
          bison
          flex
          make
          mingw-w64-${{matrix.env}}-gcc
    - uses: actions/checkout@v7
    - run: make CC=gcc
    - run: make check
    - name: Dump testsuite log
      if: failure()
      run: cat ptest/testsuite.log
